import type { MapEntry } from "@/lib/stack-map/types";

// Backend here means application logic that isn't UI, so CLI frameworks live here too.
// dropWhenDevOnly is set on HTTP servers, CLI frameworks, HTTP clients and service SDKs.
// Frameworks (Rails, Laravel, Django, FastAPI) and ORMs are unflagged: a dev-declared
// framework usually means the repo is a plugin for it, and ORM CLIs ship as devDependencies.
export const BACKEND: MapEntry[] = [
  {
    id: "node",
    display: "Node",
    symbol: "No",
    category: "backend",
    weight: 70,
    description: "JavaScript runtime.",
    aliases: ["tool:node", "docker:node", "action:actions/setup-node"],
  },
  {
    id: "deno",
    display: "Deno",
    symbol: "De",
    category: "backend",
    weight: 72,
    description: "Secure-by-default JavaScript and TypeScript runtime.",
    aliases: ["tool:deno", "docker:denoland/deno", "action:denoland/setup-deno"],
  },
  {
    // The header already names the primary language; these carry the version and
    // cover a secondary language, so they rank low.
    id: "python",
    display: "Python",
    symbol: "Py",
    category: "backend",
    weight: 45,
    description: "Python runtime.",
    aliases: ["tool:python", "docker:python", "action:actions/setup-python"],
    versionPrecision: "minor",
  },
  {
    id: "go",
    display: "Go",
    symbol: "Go",
    category: "backend",
    weight: 45,
    description: "Go toolchain.",
    aliases: ["tool:go", "docker:golang", "action:actions/setup-go"],
    versionPrecision: "minor",
  },
  {
    id: "rust",
    display: "Rust",
    symbol: "Rs",
    category: "backend",
    weight: 45,
    description: "Rust toolchain.",
    aliases: ["tool:rust", "docker:rust", "action:dtolnay/rust-toolchain", "action:actions-rust-lang/setup-rust-toolchain"],
    versionPrecision: "minor",
  },
  {
    id: "ruby",
    display: "Ruby",
    symbol: "Rb",
    category: "backend",
    weight: 45,
    description: "Ruby runtime.",
    aliases: ["tool:ruby", "docker:ruby", "action:ruby/setup-ruby"],
  },
  {
    id: "php",
    display: "PHP",
    symbol: "Ph",
    category: "backend",
    weight: 45,
    description: "PHP runtime.",
    aliases: ["tool:php", "docker:php", "action:shivammathur/setup-php"],
  },
  {
    id: "java",
    display: "Java",
    symbol: "Ja",
    category: "backend",
    weight: 45,
    description: "Java runtime.",
    aliases: ["docker:eclipse-temurin", "docker:openjdk", "docker:amazoncorretto", "action:actions/setup-java"],
  },
  {
    id: "express",
    display: "Express",
    symbol: "Ep",
    category: "backend",
    weight: 80,
    description: "Minimal Node web framework.",
    aliases: ["npm:express"],
    dropWhenDevOnly: true,
  },
  {
    id: "fastify",
    display: "Fastify",
    symbol: "Fs",
    category: "backend",
    weight: 82,
    description: "Fast, schema-driven Node web framework.",
    aliases: ["npm:fastify"],
    dropWhenDevOnly: true,
  },
  {
    id: "koa",
    display: "Koa",
    symbol: "Ko",
    category: "backend",
    weight: 76,
    description: "Middleware-first Node web framework.",
    aliases: ["npm:koa"],
    dropWhenDevOnly: true,
  },
  {
    id: "hono",
    display: "Hono",
    symbol: "Ho",
    category: "backend",
    weight: 82,
    description: "Small web framework for any JavaScript runtime.",
    aliases: ["npm:hono"],
    dropWhenDevOnly: true,
  },
  {
    id: "nestjs",
    display: "NestJS",
    symbol: "Ns",
    category: "backend",
    weight: 90,
    description: "Structured Node framework with dependency injection.",
    aliases: ["npm:@nestjs/*"],
    suppresses: ["express", "fastify"],
  },
  {
    id: "trpc",
    display: "tRPC",
    symbol: "Tp",
    category: "backend",
    weight: 72,
    description: "End-to-end type-safe APIs without a schema.",
    aliases: ["npm:@trpc/*"],
  },
  {
    id: "graphql",
    display: "GraphQL",
    symbol: "Gp",
    category: "backend",
    weight: 66,
    description: "Query language for APIs.",
    aliases: ["npm:graphql", "pypi:graphene", "pypi:strawberry-graphql", "gem:graphql"],
  },
  {
    id: "apollo-server",
    display: "Apollo Server",
    symbol: "Ap",
    category: "backend",
    weight: 72,
    description: "GraphQL server for Node.",
    aliases: ["npm:@apollo/server", "npm:apollo-server"],
    suppresses: ["graphql"],
    dropWhenDevOnly: true,
  },
  {
    id: "socket-io",
    display: "Socket.IO",
    symbol: "Sf",
    category: "backend",
    weight: 60,
    description: "Realtime bidirectional events.",
    aliases: ["npm:socket.io", "npm:socket.io-client"],
    dropWhenDevOnly: true,
  },
  {
    id: "grpc",
    display: "gRPC",
    symbol: "Gg",
    category: "backend",
    weight: 64,
    description: "RPC framework over HTTP/2 and protobuf.",
    aliases: ["npm:@grpc/grpc-js", "pypi:grpcio", "go:google.golang.org/grpc", "cargo:tonic"],
  },
  {
    // An ORM defines the data model the app is built around; it isn't dev tooling.
    id: "prisma",
    display: "Prisma",
    symbol: "Pi",
    category: "backend",
    weight: 78,
    description: "Typed ORM and migration tool.",
    aliases: ["npm:prisma", "npm:@prisma/client"],
  },
  {
    id: "drizzle",
    display: "Drizzle",
    symbol: "Dr",
    category: "backend",
    weight: 78,
    description: "SQL-shaped TypeScript ORM.",
    aliases: ["npm:drizzle-orm", "npm:drizzle-kit"],
    versionFrom: ["npm:drizzle-orm"],
  },
  {
    id: "typeorm",
    display: "TypeORM",
    symbol: "Ty",
    category: "backend",
    weight: 72,
    description: "Decorator-based ORM for TypeScript.",
    aliases: ["npm:typeorm"],
  },
  {
    id: "sequelize",
    display: "Sequelize",
    symbol: "Sz",
    category: "backend",
    weight: 70,
    description: "Promise-based Node ORM.",
    aliases: ["npm:sequelize"],
  },
  {
    id: "mongoose",
    display: "Mongoose",
    symbol: "Mn",
    category: "backend",
    weight: 74,
    description: "MongoDB object modelling for Node.",
    aliases: ["npm:mongoose"],
  },
  {
    id: "kysely",
    display: "Kysely",
    symbol: "Ky",
    category: "backend",
    weight: 68,
    description: "Type-safe SQL query builder.",
    aliases: ["npm:kysely"],
  },
  {
    id: "knex",
    display: "Knex",
    symbol: "Kn",
    category: "backend",
    weight: 64,
    description: "SQL query builder for Node.",
    aliases: ["npm:knex"],
  },
  {
    // Drivers imply the database: a project with `pg` runs PostgreSQL somewhere.
    id: "postgres",
    display: "PostgreSQL",
    symbol: "Po",
    category: "backend",
    weight: 82,
    description: "Relational database.",
    aliases: [
      "npm:pg",
      "npm:postgres",
      "pypi:psycopg",
      "pypi:psycopg2",
      "pypi:psycopg2-binary",
      "pypi:asyncpg",
      "gem:pg",
      "go:github.com/jackc/pgx*",
      "go:github.com/lib/pq",
      "cargo:tokio-postgres",
      "cargo:postgres",
      "docker:postgres",
      "docker:postgis/postgis",
      "docker:bitnami/postgresql",
    ],
    runtimeOnly: true,
    versionFrom: ["docker:*"],
  },
  {
    id: "mysql",
    display: "MySQL",
    symbol: "My",
    category: "backend",
    weight: 80,
    description: "Relational database.",
    aliases: [
      "npm:mysql2",
      "npm:mysql",
      "pypi:mysqlclient",
      "pypi:pymysql",
      "gem:mysql2",
      "go:github.com/go-sql-driver/mysql",
      "docker:mysql",
      "docker:bitnami/mysql",
    ],
    runtimeOnly: true,
    versionFrom: ["docker:*"],
  },
  {
    id: "mariadb",
    display: "MariaDB",
    symbol: "Ma",
    category: "backend",
    weight: 80,
    description: "MySQL-compatible relational database.",
    aliases: ["npm:mariadb", "docker:mariadb"],
    runtimeOnly: true,
    versionFrom: ["docker:*"],
  },
  {
    id: "sqlite",
    display: "SQLite",
    symbol: "St",
    category: "backend",
    weight: 74,
    description: "Embedded relational database.",
    aliases: [
      "npm:better-sqlite3",
      "npm:sqlite3",
      "npm:@libsql/client",
      "gem:sqlite3",
      "go:modernc.org/sqlite",
      "go:github.com/mattn/go-sqlite3",
      "cargo:rusqlite",
    ],
    runtimeOnly: true,
    versionFrom: [],
  },
  {
    id: "mongodb",
    display: "MongoDB",
    symbol: "Mo",
    category: "backend",
    weight: 80,
    description: "Document database.",
    aliases: ["npm:mongodb", "pypi:pymongo", "pypi:motor", "gem:mongoid", "go:go.mongodb.org/mongo-driver*", "docker:mongo"],
    runtimeOnly: true,
    versionFrom: ["docker:*"],
  },
  {
    id: "redis",
    display: "Redis",
    symbol: "Rd",
    category: "backend",
    weight: 72,
    description: "In-memory data store and cache.",
    aliases: [
      "npm:redis",
      "npm:ioredis",
      "pypi:redis",
      "gem:redis",
      "gem:hiredis-client",
      "go:github.com/redis/go-redis*",
      "cargo:redis",
      "docker:redis",
      "docker:valkey/valkey",
    ],
    runtimeOnly: true,
    versionFrom: ["docker:*"],
  },
  {
    id: "elasticsearch",
    display: "Elasticsearch",
    symbol: "Ea",
    category: "backend",
    weight: 70,
    description: "Search and analytics engine.",
    aliases: ["npm:@elastic/elasticsearch", "pypi:elasticsearch", "gem:chewy", "gem:elasticsearch", "docker:elasticsearch"],
    runtimeOnly: true,
    versionFrom: ["docker:*"],
  },
  {
    id: "rabbitmq",
    display: "RabbitMQ",
    symbol: "Ri",
    category: "backend",
    weight: 66,
    description: "Message broker.",
    aliases: ["npm:amqplib", "pypi:pika", "gem:bunny", "docker:rabbitmq"],
    runtimeOnly: true,
    versionFrom: ["docker:*"],
  },
  {
    id: "kafka",
    display: "Kafka",
    symbol: "Ka",
    category: "backend",
    weight: 68,
    description: "Distributed event streaming.",
    aliases: ["npm:kafkajs", "pypi:kafka-python", "pypi:confluent-kafka", "docker:confluentinc/cp-kafka", "docker:apache/kafka"],
    runtimeOnly: true,
    versionFrom: ["docker:*"],
  },
  {
    id: "django",
    display: "Django",
    symbol: "Dj",
    category: "backend",
    weight: 95,
    description: "Batteries-included Python web framework.",
    aliases: ["pypi:django"],
  },
  {
    id: "django-rest-framework",
    display: "DRF",
    symbol: "Df",
    category: "backend",
    weight: 76,
    description: "Django REST framework for web APIs.",
    aliases: ["pypi:djangorestframework"],
  },
  {
    id: "flask",
    display: "Flask",
    symbol: "Fl",
    category: "backend",
    weight: 90,
    description: "Lightweight Python web framework.",
    aliases: ["pypi:flask"],
  },
  {
    id: "fastapi",
    display: "FastAPI",
    symbol: "Fa",
    category: "backend",
    weight: 94,
    description: "Async Python API framework driven by type hints.",
    aliases: ["pypi:fastapi"],
    suppresses: ["starlette"],
  },
  {
    id: "starlette",
    display: "Starlette",
    symbol: "Sr",
    category: "backend",
    weight: 70,
    description: "Lightweight ASGI framework.",
    aliases: ["pypi:starlette"],
  },
  {
    id: "sqlalchemy",
    display: "SQLAlchemy",
    symbol: "Sc",
    category: "backend",
    weight: 74,
    description: "Python SQL toolkit and ORM.",
    aliases: ["pypi:sqlalchemy", "pypi:flask-sqlalchemy"],
    versionFrom: ["pypi:sqlalchemy"],
  },
  {
    id: "sqlmodel",
    display: "SQLModel",
    symbol: "Sq",
    category: "backend",
    weight: 76,
    description: "SQL models from Pydantic types, on SQLAlchemy.",
    aliases: ["pypi:sqlmodel"],
    suppresses: ["sqlalchemy"],
  },
  {
    id: "alembic",
    display: "Alembic",
    symbol: "Ae",
    category: "backend",
    weight: 50,
    description: "Database migrations for SQLAlchemy.",
    aliases: ["pypi:alembic"],
  },
  {
    id: "pydantic",
    display: "Pydantic",
    symbol: "Pd",
    category: "backend",
    weight: 62,
    description: "Data validation from Python type hints.",
    aliases: ["pypi:pydantic", "pypi:pydantic-settings"],
    versionFrom: ["pypi:pydantic"],
  },
  {
    id: "celery",
    display: "Celery",
    symbol: "Ce",
    category: "backend",
    weight: 72,
    description: "Distributed task queue.",
    aliases: ["pypi:celery"],
  },
  {
    id: "uvicorn",
    display: "Uvicorn",
    symbol: "Ui",
    category: "backend",
    weight: 42,
    description: "ASGI server.",
    aliases: ["pypi:uvicorn"],
    dropWhenDevOnly: true,
  },
  {
    id: "gunicorn",
    display: "Gunicorn",
    symbol: "Gu",
    category: "backend",
    weight: 40,
    description: "WSGI HTTP server.",
    aliases: ["pypi:gunicorn"],
    dropWhenDevOnly: true,
  },
  {
    id: "numpy",
    display: "NumPy",
    symbol: "Nm",
    category: "backend",
    weight: 64,
    description: "N-dimensional arrays and numerics.",
    aliases: ["pypi:numpy"],
  },
  {
    id: "pandas",
    display: "pandas",
    symbol: "Pa",
    category: "backend",
    weight: 66,
    description: "Dataframes for data analysis.",
    aliases: ["pypi:pandas"],
  },
  {
    id: "pytorch",
    display: "PyTorch",
    symbol: "Pt",
    category: "backend",
    weight: 84,
    description: "Deep learning framework.",
    aliases: ["pypi:torch"],
  },
  {
    id: "tensorflow",
    display: "TensorFlow",
    symbol: "Te",
    category: "backend",
    weight: 82,
    description: "Machine learning platform.",
    aliases: ["pypi:tensorflow", "npm:@tensorflow/tfjs"],
  },
  {
    id: "scikit-learn",
    display: "scikit-learn",
    symbol: "Sk",
    category: "backend",
    weight: 72,
    description: "Classical machine learning.",
    aliases: ["pypi:scikit-learn"],
  },
  {
    id: "httpx",
    display: "HTTPX",
    symbol: "Hp",
    category: "backend",
    weight: 34,
    description: "Async-capable HTTP client for Python.",
    aliases: ["pypi:httpx"],
    dropWhenDevOnly: true,
  },
  {
    id: "requests",
    display: "Requests",
    symbol: "Rq",
    category: "backend",
    weight: 32,
    description: "HTTP client for Python.",
    aliases: ["pypi:requests"],
    dropWhenDevOnly: true,
  },
  {
    id: "typer",
    display: "Typer",
    symbol: "Tc",
    category: "backend",
    weight: 50,
    description: "CLI apps from Python type hints.",
    aliases: ["pypi:typer"],
    suppresses: ["click"],
    dropWhenDevOnly: true,
  },
  {
    id: "click",
    display: "Click",
    symbol: "Ci",
    category: "backend",
    weight: 46,
    description: "Composable Python CLIs.",
    aliases: ["pypi:click"],
    dropWhenDevOnly: true,
  },
  {
    id: "gin",
    display: "Gin",
    symbol: "Gi",
    category: "backend",
    weight: 88,
    description: "Go HTTP web framework.",
    aliases: ["go:github.com/gin-gonic/gin"],
  },
  {
    id: "echo",
    display: "Echo",
    symbol: "Ec",
    category: "backend",
    weight: 86,
    description: "Minimal Go web framework.",
    aliases: ["go:github.com/labstack/echo*"],
  },
  {
    id: "fiber",
    display: "Fiber",
    symbol: "Fi",
    category: "backend",
    weight: 86,
    description: "Express-inspired Go web framework.",
    aliases: ["go:github.com/gofiber/fiber*"],
  },
  {
    id: "chi",
    display: "chi",
    symbol: "Ch",
    category: "backend",
    weight: 80,
    description: "Lightweight Go HTTP router.",
    aliases: ["go:github.com/go-chi/chi*"],
  },
  {
    id: "gorm",
    display: "GORM",
    symbol: "Gr",
    category: "backend",
    weight: 74,
    description: "ORM for Go.",
    aliases: ["go:gorm.io/gorm"],
  },
  {
    id: "cobra",
    display: "Cobra",
    symbol: "Cb",
    category: "backend",
    weight: 56,
    description: "Go CLI framework.",
    aliases: ["go:github.com/spf13/cobra"],
    dropWhenDevOnly: true,
  },
  {
    id: "tokio",
    display: "Tokio",
    symbol: "Tk",
    category: "backend",
    weight: 66,
    description: "Async runtime for Rust.",
    aliases: ["cargo:tokio"],
  },
  {
    id: "axum",
    display: "Axum",
    symbol: "Ax",
    category: "backend",
    weight: 88,
    description: "Rust web framework on Tokio and Tower.",
    aliases: ["cargo:axum"],
    suppresses: ["tokio"],
  },
  {
    id: "actix-web",
    display: "Actix Web",
    symbol: "Aw",
    category: "backend",
    weight: 88,
    description: "Rust web framework.",
    aliases: ["cargo:actix-web"],
  },
  {
    id: "rocket",
    display: "Rocket",
    symbol: "Ro",
    category: "backend",
    weight: 86,
    description: "Rust web framework.",
    aliases: ["cargo:rocket"],
  },
  {
    id: "sqlx",
    display: "SQLx",
    symbol: "Sx",
    category: "backend",
    weight: 70,
    description: "Compile-time checked SQL for Rust.",
    aliases: ["cargo:sqlx"],
  },
  {
    id: "diesel",
    display: "Diesel",
    symbol: "Di",
    category: "backend",
    weight: 70,
    description: "ORM and query builder for Rust.",
    aliases: ["cargo:diesel"],
  },
  {
    id: "serde",
    display: "Serde",
    symbol: "Sd",
    category: "backend",
    weight: 36,
    description: "Rust serialization framework.",
    aliases: ["cargo:serde"],
  },
  {
    id: "clap",
    display: "clap",
    symbol: "Cl",
    category: "backend",
    weight: 50,
    description: "Rust command-line argument parser.",
    aliases: ["cargo:clap"],
    dropWhenDevOnly: true,
  },
  {
    // napi-rs is how a Rust core ships as a Node package (next.js's SWC bindings).
    id: "napi-rs",
    display: "napi-rs",
    symbol: "Na",
    category: "backend",
    weight: 52,
    description: "Node addons written in Rust.",
    aliases: ["cargo:napi", "npm:@napi-rs/cli"],
  },
  {
    id: "rails",
    display: "Rails",
    symbol: "Ra",
    category: "backend",
    weight: 95,
    description: "Full-stack Ruby web framework.",
    aliases: ["gem:rails"],
  },
  {
    id: "sinatra",
    display: "Sinatra",
    symbol: "Si",
    category: "backend",
    weight: 84,
    description: "Minimal Ruby web framework.",
    aliases: ["gem:sinatra"],
  },
  {
    id: "sidekiq",
    display: "Sidekiq",
    symbol: "Ss",
    category: "backend",
    weight: 72,
    description: "Background jobs for Ruby on Redis.",
    aliases: ["gem:sidekiq"],
  },
  {
    id: "puma",
    display: "Puma",
    symbol: "Px",
    category: "backend",
    weight: 40,
    description: "Ruby web server.",
    aliases: ["gem:puma"],
  },
  {
    id: "devise",
    display: "Devise",
    symbol: "Dv",
    category: "backend",
    weight: 56,
    description: "Authentication for Rails.",
    aliases: ["gem:devise"],
  },
  {
    id: "laravel",
    display: "Laravel",
    symbol: "La",
    category: "backend",
    weight: 95,
    description: "Full-stack PHP web framework.",
    aliases: ["composer:laravel/framework"],
  },
  {
    id: "symfony",
    display: "Symfony",
    symbol: "Sy",
    category: "backend",
    weight: 92,
    description: "PHP framework and reusable components.",
    aliases: ["composer:symfony/framework-bundle", "composer:symfony/symfony"],
  },
  {
    id: "doctrine",
    display: "Doctrine",
    symbol: "Dc",
    category: "backend",
    weight: 70,
    description: "ORM for PHP.",
    aliases: ["composer:doctrine/orm"],
  },
  {
    id: "openai",
    display: "OpenAI SDK",
    symbol: "Os",
    category: "backend",
    weight: 70,
    description: "Client for the OpenAI API.",
    aliases: ["npm:openai", "pypi:openai"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "anthropic",
    display: "Anthropic SDK",
    symbol: "At",
    category: "backend",
    weight: 70,
    description: "Client for the Claude API.",
    aliases: ["npm:@anthropic-ai/sdk", "pypi:anthropic"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "ai-sdk",
    display: "AI SDK",
    symbol: "Ai",
    category: "backend",
    weight: 70,
    description: "Vercel's TypeScript toolkit for LLM apps.",
    aliases: ["npm:ai", "npm:@ai-sdk/*"],
    versionFrom: ["npm:ai"],
    dropWhenDevOnly: true,
  },
  {
    id: "langchain",
    display: "LangChain",
    symbol: "Ln",
    category: "backend",
    weight: 70,
    description: "Framework for LLM applications.",
    aliases: ["npm:langchain", "npm:@langchain/*", "pypi:langchain", "pypi:langchain-*"],
    versionFrom: ["npm:langchain", "pypi:langchain"],
    dropWhenDevOnly: true,
  },
  {
    id: "auth-js",
    display: "Auth.js",
    symbol: "Au",
    category: "backend",
    weight: 62,
    description: "Authentication for web frameworks, formerly NextAuth.",
    aliases: ["npm:next-auth", "npm:@auth/*"],
    versionFrom: ["npm:next-auth"],
  },
  {
    id: "better-auth",
    display: "Better Auth",
    symbol: "Ba",
    category: "backend",
    weight: 62,
    description: "TypeScript authentication framework.",
    aliases: ["npm:better-auth"],
  },
  {
    id: "clerk",
    display: "Clerk",
    symbol: "Cr",
    category: "backend",
    weight: 62,
    description: "Hosted authentication and user management.",
    aliases: ["npm:@clerk/*"],
    versionFrom: [],
  },
  {
    id: "passport",
    display: "Passport",
    symbol: "Pj",
    category: "backend",
    weight: 56,
    description: "Authentication middleware for Node.",
    aliases: ["npm:passport"],
  },
  {
    id: "stripe",
    display: "Stripe",
    symbol: "Sp",
    category: "backend",
    weight: 64,
    description: "Payments API client.",
    aliases: ["npm:stripe", "npm:@stripe/*", "pypi:stripe", "gem:stripe", "composer:stripe/stripe-php"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "pdfkit",
    display: "PDFKit",
    symbol: "Pf",
    category: "backend",
    weight: 60,
    description: "PDF generation for Node.",
    aliases: ["npm:pdfkit"],
  },
  {
    // Headless Chrome is usually app functionality (PDFs, scraping), not a test runner.
    id: "puppeteer",
    display: "Puppeteer",
    symbol: "Pu",
    category: "backend",
    weight: 60,
    description: "Headless Chrome automation.",
    aliases: ["npm:puppeteer", "npm:puppeteer-core"],
  },
  {
    // Backend, not frontend: it runs on the server at request time and never ships to a
    // browser. Not tooling either — the images are the product, not a build artifact.
    id: "satori",
    display: "Satori",
    symbol: "Sb",
    category: "backend",
    weight: 60,
    description: "Renders HTML and CSS to SVG, for server-generated images.",
    aliases: ["npm:satori"],
  },
  {
    // Same argument as satori, and it sits directly downstream of it. Kept separate
    // rather than suppressed: two libraries, two steps, and a repo can use either alone.
    id: "resvg",
    display: "resvg",
    symbol: "Rv",
    category: "backend",
    weight: 55,
    description: "Rasterizes SVG to PNG, as a native Node binding.",
    aliases: ["npm:@resvg/resvg-js", "cargo:resvg"],
    versionFrom: ["npm:@resvg/resvg-js"],
  },
  {
    id: "axios",
    display: "Axios",
    symbol: "Ao",
    category: "backend",
    weight: 30,
    description: "Promise-based HTTP client.",
    aliases: ["npm:axios"],
    dropWhenDevOnly: true,
  },
];
