import type { MapEntry } from "@/lib/stack-map/types";

export const FRONTEND: MapEntry[] = [
  {
    id: "next",
    display: "Next.js",
    category: "frontend",
    weight: 95,
    description: "React framework with file-based routing and server rendering.",
    aliases: ["npm:next"],
    suppresses: ["react"],
  },
  {
    id: "nuxt",
    display: "Nuxt",
    category: "frontend",
    weight: 95,
    description: "Vue framework with file-based routing and server rendering.",
    aliases: ["npm:nuxt"],
    suppresses: ["vue"],
  },
  {
    id: "sveltekit",
    display: "SvelteKit",
    category: "frontend",
    weight: 95,
    description: "Svelte application framework with routing and server rendering.",
    aliases: ["npm:@sveltejs/kit"],
    suppresses: ["svelte"],
  },
  {
    id: "remix",
    display: "Remix",
    category: "frontend",
    weight: 94,
    description: "Full-stack React framework built on web fetch primitives.",
    aliases: ["npm:@remix-run/*"],
    suppresses: ["react", "react-router"],
  },
  {
    id: "astro",
    display: "Astro",
    category: "frontend",
    weight: 94,
    description: "Content-first site framework that ships zero JS by default.",
    aliases: ["npm:astro"],
  },
  {
    id: "gatsby",
    display: "Gatsby",
    category: "frontend",
    weight: 92,
    description: "React static site generator with a GraphQL data layer.",
    aliases: ["npm:gatsby"],
    suppresses: ["react"],
  },
  {
    id: "solid-start",
    display: "SolidStart",
    category: "frontend",
    weight: 93,
    description: "Solid application framework with routing and server rendering.",
    aliases: ["npm:@solidjs/start"],
    suppresses: ["solid"],
  },
  {
    id: "expo",
    display: "Expo",
    category: "frontend",
    weight: 93,
    description: "Framework and tooling for React Native apps.",
    aliases: ["npm:expo"],
    suppresses: ["react-native", "react"],
  },
  {
    id: "react",
    display: "React",
    category: "frontend",
    weight: 90,
    description: "Component library for building user interfaces.",
    aliases: ["npm:react", "npm:react-dom"],
  },
  {
    id: "vue",
    display: "Vue",
    category: "frontend",
    weight: 90,
    description: "Progressive framework for building user interfaces.",
    aliases: ["npm:vue"],
  },
  {
    id: "svelte",
    display: "Svelte",
    category: "frontend",
    weight: 90,
    description: "Compiler-based UI framework.",
    aliases: ["npm:svelte"],
  },
  {
    id: "angular",
    display: "Angular",
    category: "frontend",
    weight: 92,
    description: "Batteries-included TypeScript application framework.",
    aliases: ["npm:@angular/*"],
  },
  {
    id: "solid",
    display: "Solid",
    category: "frontend",
    weight: 88,
    description: "Reactive UI library with fine-grained signals.",
    aliases: ["npm:solid-js"],
  },
  {
    id: "preact",
    display: "Preact",
    category: "frontend",
    weight: 86,
    description: "Small React-compatible UI library.",
    aliases: ["npm:preact"],
  },
  {
    id: "react-native",
    display: "React Native",
    category: "frontend",
    weight: 91,
    description: "React for native iOS and Android apps.",
    aliases: ["npm:react-native"],
    suppresses: ["react"],
  },
  {
    // Desktop shells render UI, so they sit with the UI rather than infra.
    id: "electron",
    display: "Electron",
    category: "frontend",
    weight: 88,
    description: "Desktop apps from web technologies on Chromium and Node.",
    aliases: ["npm:electron"],
  },
  {
    id: "tauri",
    display: "Tauri",
    category: "frontend",
    weight: 88,
    description: "Desktop apps with a web UI and a Rust core.",
    aliases: ["npm:@tauri-apps/*", "cargo:tauri"],
  },
  {
    id: "lit",
    display: "Lit",
    category: "frontend",
    weight: 82,
    description: "Web components with reactive properties.",
    aliases: ["npm:lit"],
  },
  {
    id: "qwik",
    display: "Qwik",
    category: "frontend",
    weight: 88,
    description: "Resumable framework that defers JS until interaction.",
    aliases: ["npm:@builder.io/qwik", "npm:@qwik.dev/core"],
  },
  {
    id: "react-router",
    display: "React Router",
    category: "frontend",
    weight: 72,
    description: "Routing for React apps; framework mode since v7.",
    aliases: ["npm:react-router", "npm:react-router-dom"],
  },
  {
    id: "tanstack-router",
    display: "TanStack Router",
    category: "frontend",
    weight: 70,
    description: "Type-safe router for React.",
    aliases: ["npm:@tanstack/react-router", "npm:@tanstack/react-start"],
  },
  {
    id: "hotwire",
    display: "Hotwire",
    category: "frontend",
    weight: 80,
    description: "HTML-over-the-wire: Turbo and Stimulus.",
    aliases: ["gem:turbo-rails", "gem:stimulus-rails", "npm:@hotwired/*"],
    versionFrom: [],
  },
  {
    // Rendered by the backend, but it is the frontend's programming model.
    id: "htmx",
    display: "htmx",
    category: "frontend",
    weight: 80,
    description: "Hypermedia controls via HTML attributes.",
    aliases: ["npm:htmx.org"],
  },
  {
    id: "alpine",
    display: "Alpine.js",
    category: "frontend",
    weight: 76,
    description: "Small reactive behaviour declared in markup.",
    aliases: ["npm:alpinejs"],
  },
  {
    id: "jquery",
    display: "jQuery",
    category: "frontend",
    weight: 60,
    description: "DOM manipulation and events library.",
    aliases: ["npm:jquery", "gem:jquery-rails"],
  },
  {
    id: "inertia",
    display: "Inertia",
    category: "frontend",
    weight: 82,
    description: "Server-driven SPAs without a separate API.",
    aliases: ["npm:@inertiajs/*", "composer:inertiajs/inertia-laravel"],
  },
  {
    id: "livewire",
    display: "Livewire",
    category: "frontend",
    weight: 82,
    description: "Reactive Laravel components rendered on the server.",
    aliases: ["composer:livewire/livewire"],
  },
  {
    id: "tailwindcss",
    display: "Tailwind",
    category: "frontend",
    weight: 78,
    description: "Utility-first CSS framework.",
    aliases: ["npm:tailwindcss", "npm:@tailwindcss/*", "gem:tailwindcss-rails"],
    suppresses: ["postcss", "autoprefixer"],
    versionFrom: ["npm:tailwindcss", "npm:@tailwindcss/*"],
  },
  {
    id: "sass",
    display: "Sass",
    category: "frontend",
    weight: 55,
    description: "CSS preprocessor.",
    aliases: ["npm:sass", "npm:sass-embedded", "npm:node-sass"],
  },
  {
    id: "styled-components",
    display: "styled-components",
    category: "frontend",
    weight: 62,
    description: "CSS-in-JS with tagged template literals.",
    aliases: ["npm:styled-components"],
  },
  {
    id: "emotion",
    display: "Emotion",
    category: "frontend",
    weight: 60,
    description: "CSS-in-JS library.",
    aliases: ["npm:@emotion/*"],
  },
  {
    id: "bootstrap",
    display: "Bootstrap",
    category: "frontend",
    weight: 62,
    description: "Component CSS framework.",
    aliases: ["npm:bootstrap", "gem:bootstrap"],
  },
  {
    // shadcn/ui ships as copied source, so Radix is what the manifest shows.
    id: "radix-ui",
    display: "Radix UI",
    category: "frontend",
    weight: 64,
    description: "Unstyled, accessible UI primitives.",
    aliases: ["npm:@radix-ui/*", "npm:radix-ui"],
    versionFrom: [],
  },
  {
    id: "mui",
    display: "MUI",
    category: "frontend",
    weight: 66,
    description: "Material Design React components.",
    aliases: ["npm:@mui/*"],
  },
  {
    id: "chakra-ui",
    display: "Chakra UI",
    category: "frontend",
    weight: 64,
    description: "Accessible React component library.",
    aliases: ["npm:@chakra-ui/*"],
  },
  {
    id: "mantine",
    display: "Mantine",
    category: "frontend",
    weight: 64,
    description: "React components and hooks library.",
    aliases: ["npm:@mantine/*"],
  },
  {
    id: "ant-design",
    display: "Ant Design",
    category: "frontend",
    weight: 64,
    description: "Enterprise React component library.",
    aliases: ["npm:antd"],
  },
  {
    id: "headless-ui",
    display: "Headless UI",
    category: "frontend",
    weight: 56,
    description: "Unstyled accessible components from Tailwind Labs.",
    aliases: ["npm:@headlessui/*"],
  },
  {
    id: "motion",
    display: "Motion",
    category: "frontend",
    weight: 52,
    description: "Animation library, formerly Framer Motion.",
    aliases: ["npm:framer-motion", "npm:motion"],
  },
  {
    id: "lucide",
    display: "Lucide",
    category: "frontend",
    weight: 30,
    description: "Icon set.",
    aliases: ["npm:lucide-react", "npm:lucide-vue-next", "npm:lucide", "npm:lucide-svelte"],
    versionFrom: [],
  },
  {
    id: "redux",
    display: "Redux",
    category: "frontend",
    weight: 66,
    description: "Predictable state container.",
    aliases: ["npm:redux", "npm:@reduxjs/toolkit", "npm:react-redux"],
    versionFrom: ["npm:redux", "npm:@reduxjs/toolkit"],
  },
  {
    id: "zustand",
    display: "Zustand",
    category: "frontend",
    weight: 62,
    description: "Small hook-based state store.",
    aliases: ["npm:zustand"],
  },
  {
    id: "jotai",
    display: "Jotai",
    category: "frontend",
    weight: 58,
    description: "Atomic state for React.",
    aliases: ["npm:jotai"],
  },
  {
    id: "mobx",
    display: "MobX",
    category: "frontend",
    weight: 58,
    description: "Observable state management.",
    aliases: ["npm:mobx"],
  },
  {
    id: "pinia",
    display: "Pinia",
    category: "frontend",
    weight: 60,
    description: "State store for Vue.",
    aliases: ["npm:pinia"],
  },
  {
    id: "tanstack-query",
    display: "TanStack Query",
    category: "frontend",
    weight: 66,
    description: "Server-state cache for async data.",
    aliases: [
      "npm:@tanstack/react-query",
      "npm:@tanstack/vue-query",
      "npm:@tanstack/svelte-query",
      "npm:@tanstack/solid-query",
      "npm:@tanstack/query-core",
    ],
  },
  {
    id: "swr",
    display: "SWR",
    category: "frontend",
    weight: 58,
    description: "Stale-while-revalidate data fetching hooks.",
    aliases: ["npm:swr"],
  },
  {
    id: "apollo-client",
    display: "Apollo Client",
    category: "frontend",
    weight: 62,
    description: "GraphQL client with a normalized cache.",
    aliases: ["npm:@apollo/client"],
  },
  {
    id: "react-hook-form",
    display: "React Hook Form",
    category: "frontend",
    weight: 50,
    description: "Performant form state for React.",
    aliases: ["npm:react-hook-form"],
  },
  {
    // DESIGN.md's drawing places Zod here; it runs on both sides, but it's usually
    // validating what a form or fetch hands back.
    id: "zod",
    display: "Zod",
    category: "frontend",
    weight: 54,
    description: "Schema validation with inferred types.",
    aliases: ["npm:zod"],
  },
  {
    id: "i18next",
    display: "i18next",
    category: "frontend",
    weight: 40,
    description: "Internationalization framework.",
    aliases: ["npm:i18next", "npm:react-i18next"],
    versionFrom: ["npm:i18next"],
  },
  {
    id: "d3",
    display: "D3",
    category: "frontend",
    weight: 50,
    description: "Data-driven document manipulation for visualizations.",
    aliases: ["npm:d3"],
  },
  {
    id: "three",
    display: "Three.js",
    category: "frontend",
    weight: 60,
    description: "3D graphics on WebGL.",
    aliases: ["npm:three", "npm:@react-three/fiber"],
    versionFrom: ["npm:three"],
  },
  {
    id: "chartjs",
    display: "Chart.js",
    category: "frontend",
    weight: 46,
    description: "Canvas charts.",
    aliases: ["npm:chart.js"],
  },
  {
    id: "recharts",
    display: "Recharts",
    category: "frontend",
    weight: 46,
    description: "React charts built on D3.",
    aliases: ["npm:recharts"],
  },
  {
    id: "leaflet",
    display: "Leaflet",
    category: "frontend",
    weight: 46,
    description: "Interactive maps.",
    aliases: ["npm:leaflet", "npm:react-leaflet"],
    versionFrom: ["npm:leaflet"],
  },
  {
    // Docs-site generators produce what readers see, so they sit with the UI.
    id: "vitepress",
    display: "VitePress",
    category: "frontend",
    weight: 48,
    description: "Vite-powered static docs site generator.",
    aliases: ["npm:vitepress"],
  },
  {
    id: "docusaurus",
    display: "Docusaurus",
    category: "frontend",
    weight: 48,
    description: "React-based docs site generator.",
    aliases: ["npm:@docusaurus/*"],
    suppresses: ["react"],
  },
  {
    id: "mkdocs",
    display: "MkDocs",
    category: "frontend",
    weight: 46,
    description: "Markdown docs site generator.",
    aliases: ["pypi:mkdocs", "pypi:mkdocs-material"],
    versionFrom: ["pypi:mkdocs"],
  },
];
