import type { MapEntry } from "@/lib/stack-map/types";

// Every hosted service and observability SDK here carries dropWhenDevOnly: in
// devDependencies they are integration-test fixtures, not what the project runs on.
export const INFRA: MapEntry[] = [
  {
    id: "docker",
    display: "Docker",
    category: "infra",
    weight: 74,
    description: "Containers for building and running the app.",
    aliases: ["tool:docker", "action:docker/*"],
  },
  {
    id: "github-actions",
    display: "GitHub Actions",
    category: "infra",
    weight: 58,
    description: "CI hosted alongside the repo.",
    aliases: ["tool:github-actions"],
  },
  {
    id: "github-pages",
    display: "GitHub Pages",
    category: "infra",
    weight: 62,
    description: "Static hosting from the repo.",
    aliases: ["action:actions/deploy-pages", "action:actions/upload-pages-artifact", "action:actions/configure-pages"],
  },
  {
    // @vercel/* packages (analytics, og, blob) only make sense deployed on Vercel.
    id: "vercel",
    display: "Vercel",
    category: "infra",
    weight: 80,
    description: "Deployment platform.",
    aliases: ["npm:vercel", "npm:@vercel/analytics", "npm:@vercel/speed-insights", "npm:@vercel/blob", "npm:@vercel/kv", "npm:@vercel/postgres", "action:amondnet/vercel-action"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "netlify",
    display: "Netlify",
    category: "infra",
    weight: 78,
    description: "Deployment platform.",
    aliases: ["npm:netlify-cli", "npm:@netlify/*"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "cloudflare",
    display: "Cloudflare",
    category: "infra",
    weight: 80,
    description: "Workers, Pages and edge platform.",
    aliases: ["npm:wrangler", "npm:@cloudflare/*", "action:cloudflare/wrangler-action", "action:cloudflare/pages-action"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "aws",
    display: "AWS",
    category: "infra",
    weight: 78,
    description: "Amazon Web Services.",
    aliases: [
      "npm:@aws-sdk/*",
      "npm:aws-sdk",
      "npm:aws-cdk-lib",
      "npm:sst",
      "pypi:boto3",
      "gem:aws-sdk-*",
      "go:github.com/aws/aws-sdk-go*",
      "cargo:aws-sdk-*",
      "action:aws-actions/*",
    ],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "gcp",
    display: "Google Cloud",
    category: "infra",
    weight: 76,
    description: "Google Cloud Platform.",
    aliases: ["npm:@google-cloud/*", "pypi:google-cloud-*", "go:cloud.google.com/go*", "action:google-github-actions/*"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "azure",
    display: "Azure",
    category: "infra",
    weight: 76,
    description: "Microsoft Azure.",
    aliases: ["npm:@azure/*", "pypi:azure-*", "action:azure/*"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "supabase",
    display: "Supabase",
    category: "infra",
    weight: 80,
    description: "Postgres platform with auth, storage and APIs.",
    aliases: ["npm:@supabase/*", "npm:supabase", "pypi:supabase", "action:supabase/setup-cli", "docker:supabase/*"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "firebase",
    display: "Firebase",
    category: "infra",
    weight: 78,
    description: "Google's app backend platform.",
    aliases: ["npm:firebase", "npm:firebase-admin", "npm:firebase-tools", "pypi:firebase-admin"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "neon",
    display: "Neon",
    category: "infra",
    weight: 70,
    description: "Serverless Postgres.",
    aliases: ["npm:@neondatabase/serverless"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "upstash",
    display: "Upstash",
    category: "infra",
    weight: 66,
    description: "Serverless Redis and queues.",
    aliases: ["npm:@upstash/*"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "fly",
    display: "Fly.io",
    category: "infra",
    weight: 76,
    description: "App hosting close to users.",
    aliases: ["action:superfly/flyctl-actions"],
  },
  {
    id: "terraform",
    display: "Terraform",
    category: "infra",
    weight: 72,
    description: "Infrastructure as code.",
    aliases: ["action:hashicorp/setup-terraform"],
  },
  {
    id: "nginx",
    display: "nginx",
    category: "infra",
    weight: 60,
    description: "Web server and reverse proxy.",
    aliases: ["docker:nginx"],
  },
  {
    id: "caddy",
    display: "Caddy",
    category: "infra",
    weight: 60,
    description: "Web server with automatic HTTPS.",
    aliases: ["docker:caddy"],
  },
  {
    // Monitoring is about the running system, not the code, so it sits in infra.
    id: "sentry",
    display: "Sentry",
    category: "infra",
    weight: 64,
    description: "Error tracking and performance monitoring.",
    aliases: ["npm:@sentry/*", "pypi:sentry-sdk", "gem:sentry-ruby", "gem:sentry-rails", "go:github.com/getsentry/sentry-go", "cargo:sentry"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "opentelemetry",
    display: "OpenTelemetry",
    category: "infra",
    weight: 58,
    description: "Vendor-neutral traces, metrics and logs.",
    aliases: ["npm:@opentelemetry/*", "pypi:opentelemetry-*", "gem:opentelemetry-*", "go:go.opentelemetry.io/otel*"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "datadog",
    display: "Datadog",
    category: "infra",
    weight: 58,
    description: "Monitoring and APM.",
    aliases: ["npm:dd-trace", "pypi:ddtrace", "gem:datadog", "gem:ddtrace"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
  {
    id: "prometheus",
    display: "Prometheus",
    category: "infra",
    weight: 56,
    description: "Metrics collection.",
    aliases: ["npm:prom-client", "gem:prometheus_exporter", "go:github.com/prometheus/client_golang", "docker:prom/prometheus"],
    versionFrom: [],
    dropWhenDevOnly: true,
  },
];
