import type { MapEntry } from "@/lib/stack-map/types";

export const TOOLING: MapEntry[] = [
  {
    // The monorepo signal ADR-0001 wants rendered; it makes plain "pnpm" redundant.
    id: "pnpm-workspaces",
    display: "pnpm workspaces",
    category: "tooling",
    weight: 82,
    description: "pnpm monorepo with multiple packages.",
    aliases: ["tool:pnpm-workspace"],
    suppresses: ["pnpm"],
  },
  {
    id: "turborepo",
    display: "Turborepo",
    category: "tooling",
    weight: 84,
    description: "Build system for JavaScript monorepos.",
    aliases: ["tool:turborepo", "npm:turbo"],
  },
  {
    id: "nx",
    display: "Nx",
    category: "tooling",
    weight: 84,
    description: "Monorepo build system.",
    aliases: ["tool:nx", "npm:nx", "npm:@nx/*"],
  },
  {
    id: "lerna",
    display: "Lerna",
    category: "tooling",
    weight: 70,
    description: "Monorepo versioning and publishing.",
    aliases: ["tool:lerna", "npm:lerna"],
  },
  {
    id: "changesets",
    display: "Changesets",
    category: "tooling",
    weight: 50,
    description: "Versioning and changelogs for packages.",
    aliases: ["npm:@changesets/cli"],
  },
  {
    id: "pnpm",
    display: "pnpm",
    category: "tooling",
    weight: 60,
    description: "Package manager with a content-addressed store.",
    aliases: ["tool:pnpm", "action:pnpm/action-setup"],
  },
  {
    id: "yarn",
    display: "Yarn",
    category: "tooling",
    weight: 58,
    description: "JavaScript package manager.",
    aliases: ["tool:yarn"],
  },
  {
    // The default, so it says the least; kept so a lone npm project isn't blank.
    id: "npm",
    display: "npm",
    category: "tooling",
    weight: 20,
    description: "Node's default package manager.",
    aliases: ["tool:npm"],
  },
  {
    // Detected from its lockfile, i.e. as a package manager; it's also a runtime.
    id: "bun",
    display: "Bun",
    category: "tooling",
    weight: 64,
    description: "JavaScript runtime, package manager and bundler.",
    aliases: ["tool:bun", "action:oven-sh/setup-bun", "docker:oven/bun"],
  },
  {
    id: "uv",
    display: "uv",
    category: "tooling",
    weight: 64,
    description: "Fast Python package and project manager.",
    aliases: ["tool:uv", "action:astral-sh/setup-uv", "pypi:uv"],
  },
  {
    id: "poetry",
    display: "Poetry",
    category: "tooling",
    weight: 60,
    description: "Python dependency management and packaging.",
    aliases: ["tool:poetry", "pypi:poetry", "pypi:poetry-core"],
  },
  {
    id: "vite",
    display: "Vite",
    category: "tooling",
    weight: 76,
    description: "Dev server and bundler.",
    aliases: ["npm:vite", "npm:laravel-vite-plugin", "npm:@vitejs/*"],
    suppresses: ["esbuild", "rollup"],
  },
  {
    id: "webpack",
    display: "webpack",
    category: "tooling",
    weight: 62,
    description: "Module bundler.",
    aliases: ["npm:webpack"],
  },
  {
    id: "esbuild",
    display: "esbuild",
    category: "tooling",
    weight: 54,
    description: "Fast JavaScript bundler.",
    aliases: ["npm:esbuild"],
  },
  {
    id: "rollup",
    display: "Rollup",
    category: "tooling",
    weight: 54,
    description: "Module bundler for libraries.",
    aliases: ["npm:rollup"],
  },
  {
    id: "parcel",
    display: "Parcel",
    category: "tooling",
    weight: 56,
    description: "Zero-config bundler.",
    aliases: ["npm:parcel"],
  },
  {
    id: "tsup",
    display: "tsup",
    category: "tooling",
    weight: 46,
    description: "TypeScript library bundler.",
    aliases: ["npm:tsup"],
  },
  {
    id: "swc",
    display: "SWC",
    category: "tooling",
    weight: 50,
    description: "Rust-based JavaScript compiler.",
    aliases: ["npm:@swc/core", "cargo:swc_core"],
  },
  {
    // The header usually names TypeScript already, so this ranks low.
    id: "typescript",
    display: "TypeScript",
    category: "tooling",
    weight: 56,
    description: "Typed JavaScript.",
    aliases: ["npm:typescript"],
  },
  {
    id: "eslint",
    display: "ESLint",
    category: "tooling",
    weight: 50,
    description: "Linter.",
    aliases: ["npm:eslint"],
  },
  {
    id: "biome",
    display: "Biome",
    category: "tooling",
    weight: 54,
    description: "Formatter and linter.",
    aliases: ["npm:@biomejs/biome"],
  },
  {
    id: "oxc",
    display: "Oxc",
    category: "tooling",
    weight: 52,
    description: "Rust-based linter and formatter.",
    aliases: ["npm:oxlint", "npm:oxfmt"],
  },
  {
    id: "prettier",
    display: "Prettier",
    category: "tooling",
    weight: 44,
    description: "Code formatter.",
    aliases: ["npm:prettier"],
  },
  {
    id: "dprint",
    display: "dprint",
    category: "tooling",
    weight: 40,
    description: "Pluggable code formatter.",
    aliases: ["npm:dprint"],
  },
  {
    id: "stylelint",
    display: "Stylelint",
    category: "tooling",
    weight: 36,
    description: "CSS linter.",
    aliases: ["npm:stylelint"],
  },
  {
    id: "postcss",
    display: "PostCSS",
    category: "tooling",
    weight: 38,
    description: "CSS transforms via plugins.",
    aliases: ["npm:postcss"],
  },
  {
    id: "autoprefixer",
    display: "Autoprefixer",
    category: "tooling",
    weight: 24,
    description: "Vendor prefixes for CSS.",
    aliases: ["npm:autoprefixer"],
  },
  {
    id: "vitest",
    display: "Vitest",
    category: "tooling",
    weight: 64,
    description: "Test runner.",
    aliases: ["npm:vitest"],
  },
  {
    id: "jest",
    display: "Jest",
    category: "tooling",
    weight: 62,
    description: "Test runner.",
    aliases: ["npm:jest"],
  },
  {
    id: "mocha",
    display: "Mocha",
    category: "tooling",
    weight: 54,
    description: "Test framework.",
    aliases: ["npm:mocha"],
  },
  {
    id: "playwright",
    display: "Playwright",
    category: "tooling",
    weight: 62,
    description: "Browser automation and end-to-end tests.",
    aliases: ["npm:playwright", "npm:@playwright/test", "npm:playwright-chromium", "pypi:playwright", "gem:playwright-ruby-client"],
  },
  {
    id: "cypress",
    display: "Cypress",
    category: "tooling",
    weight: 60,
    description: "End-to-end browser tests.",
    aliases: ["npm:cypress"],
  },
  {
    id: "testing-library",
    display: "Testing Library",
    category: "tooling",
    weight: 46,
    description: "DOM testing utilities.",
    aliases: ["npm:@testing-library/*"],
  },
  {
    id: "storybook",
    display: "Storybook",
    category: "tooling",
    weight: 56,
    description: "UI component workshop.",
    aliases: ["npm:storybook", "npm:@storybook/*"],
  },
  {
    id: "msw",
    display: "MSW",
    category: "tooling",
    weight: 40,
    description: "API mocking via service workers.",
    aliases: ["npm:msw"],
  },
  {
    id: "pytest",
    display: "pytest",
    category: "tooling",
    weight: 62,
    description: "Python test framework.",
    aliases: ["pypi:pytest"],
  },
  {
    id: "ruff",
    display: "Ruff",
    category: "tooling",
    weight: 58,
    description: "Fast Python linter and formatter.",
    aliases: ["pypi:ruff"],
  },
  {
    id: "mypy",
    display: "mypy",
    category: "tooling",
    weight: 52,
    description: "Static type checker for Python.",
    aliases: ["pypi:mypy"],
  },
  {
    id: "ty",
    display: "ty",
    category: "tooling",
    weight: 50,
    description: "Fast Python type checker.",
    aliases: ["pypi:ty"],
  },
  {
    id: "black",
    display: "Black",
    category: "tooling",
    weight: 44,
    description: "Python code formatter.",
    aliases: ["pypi:black"],
  },
  {
    id: "flake8",
    display: "Flake8",
    category: "tooling",
    weight: 38,
    description: "Python linter.",
    aliases: ["pypi:flake8"],
  },
  {
    id: "pre-commit",
    display: "pre-commit",
    category: "tooling",
    weight: 36,
    description: "Git hook framework.",
    aliases: ["pypi:pre-commit", "pypi:prek"],
  },
  {
    id: "goreleaser",
    display: "GoReleaser",
    category: "tooling",
    weight: 56,
    description: "Release automation for Go.",
    aliases: ["action:goreleaser/goreleaser-action"],
  },
  {
    id: "golangci-lint",
    display: "golangci-lint",
    category: "tooling",
    weight: 50,
    description: "Go linters runner.",
    aliases: ["action:golangci/golangci-lint-action"],
  },
  {
    id: "testify",
    display: "testify",
    category: "tooling",
    weight: 46,
    description: "Go testing toolkit.",
    aliases: ["go:github.com/stretchr/testify"],
  },
  {
    id: "insta",
    display: "insta",
    category: "tooling",
    weight: 40,
    description: "Snapshot testing for Rust.",
    aliases: ["cargo:insta"],
  },
  {
    id: "rspec",
    display: "RSpec",
    category: "tooling",
    weight: 60,
    description: "Ruby testing framework.",
    aliases: ["gem:rspec", "gem:rspec-rails"],
  },
  {
    id: "rubocop",
    display: "RuboCop",
    category: "tooling",
    weight: 50,
    description: "Ruby linter and formatter.",
    aliases: ["gem:rubocop", "gem:rubocop-*"],
  },
  {
    id: "capybara",
    display: "Capybara",
    category: "tooling",
    weight: 44,
    description: "Acceptance tests for Ruby web apps.",
    aliases: ["gem:capybara"],
  },
  {
    id: "phpunit",
    display: "PHPUnit",
    category: "tooling",
    weight: 58,
    description: "PHP testing framework.",
    aliases: ["composer:phpunit/phpunit"],
  },
  {
    id: "pest",
    display: "Pest",
    category: "tooling",
    weight: 60,
    description: "PHP testing framework.",
    aliases: ["composer:pestphp/pest"],
    suppresses: ["phpunit"],
  },
  {
    id: "pint",
    display: "Pint",
    category: "tooling",
    weight: 42,
    description: "Laravel's PHP code style fixer.",
    aliases: ["composer:laravel/pint"],
  },
  {
    id: "phpstan",
    display: "PHPStan",
    category: "tooling",
    weight: 50,
    description: "Static analysis for PHP.",
    aliases: ["composer:phpstan/phpstan", "composer:larastan/larastan"],
  },
];
