import { Footer } from "@/app/site/footer";
import { Nav } from "@/app/site/nav";
import { SnippetPitch } from "@/app/site/snippet-pitch";
import { TechIndex } from "@/app/site/tech-index";
import { StackForm } from "@/app/stack-form";
import { COPY, EXAMPLE_REPO, cardUrl } from "@/lib/site";

export default function Home() {
  return (
    <div className="flex min-h-dvh flex-col">
      <Nav />

      {/* The column is centred at roughly the card's natural width; everything inside
          starts at the card's left edge. That single shared spine does the compositional
          work a grid would do on a denser page. DESIGN.md SELF-CRITIQUE 5. */}
      <main className="mx-auto w-full max-w-275 px-4 py-16 sm:px-8 sm:py-24">
        <div className="flex flex-col items-start">
          <h1 className="site-display max-w-[16ch]">{COPY.headline}</h1>
          <p className="site-body mt-6 max-w-[68ch] text-ink-muted">{COPY.intro}</p>
          <StackForm />
        </div>
      </main>

      <SnippetPitch
        light={cardUrl(EXAMPLE_REPO.owner, EXAMPLE_REPO.repo, "tiles", "light")}
        dark={cardUrl(EXAMPLE_REPO.owner, EXAMPLE_REPO.repo, "tiles", "dark")}
        alt={`${EXAMPLE_REPO.owner}/${EXAMPLE_REPO.repo} tech stack, generated by Stackshot`}
      />

      <TechIndex />
      <Footer />
    </div>
  );
}
