import { cardFileName, type ServedStyle } from "@/lib/card-style";
import { LAYER_NAME } from "@/lib/card-text";
import type { LaunchStyle, ThemeMode } from "@/lib/preview";
import type { Theme } from "@/lib/tokens";

/**
 * The one origin the card's footer, the preview and the copied snippet all agree on.
 * Overridable so `next dev` previews its own cards; the default is what ships, and what
 * strangers' READMEs will point at forever.
 */
export const SITE_ORIGIN = process.env.NEXT_PUBLIC_SITE_ORIGIN ?? "https://stackshot.ilerioluwa.com";

/** The repo whose card stands in the empty state. One line to change. */
export const EXAMPLE_REPO = { owner: "cybprom", repo: "stackshot" };

/** Every outbound link the site has. Collected for the same reason the copy is. */
export const LINKS = {
  repo: "https://github.com/cybprom/stackshot",
  // Where a missing technology goes, from the footer and from a no-match in the index —
  // one destination, so a stranger who searched and found nothing lands where the backlog
  // already is.
  issues: "https://github.com/cybprom/stackshot/issues",
  author: "https://x.com/cybprom",
} as const;

export function cardUrl(owner: string, repo: string, style: ServedStyle, theme: Theme): string {
  return `${SITE_ORIGIN}/${owner}/${repo}/${cardFileName(style, theme)}`;
}

/**
 * The intro card's static bytes, rendered into `public/` at build time from the committed
 * doc (ADR-0035). The homepage shows these rather than `cardUrl(INTRO_REPO, …)`, because
 * the card route hits GitHub on a cold cache and the homepage must never wait on it.
 *
 * **The cost, stated because it is a real one:** M3's pre-warm — preview URL and snippet
 * URL byte-identical, so loading the preview warms the CDN entry the snippet hands out —
 * does not hold for this one card. The snippet still names the route URL. Every card a
 * visitor actually generates is unaffected.
 */
export function introCardFile(style: ServedStyle, theme: Theme): string {
  return `intro-${cardFileName(style, theme)}`;
}

export function introCardUrl(style: ServedStyle, theme: Theme): string {
  return `/${introCardFile(style, theme)}`;
}

/**
 * The README snippet. Two rules, both about what happens after someone pastes it.
 *
 * The style is always written explicitly, never left to `card-{theme}.png`, so changing
 * the site's default never restyles a card already embedded in someone's README.
 *
 * No width or height on the img: one URL serves several heights — 1200×800, the error
 * card's 1200×518, and Tiles' content height — so a snippet copied while a repo worked
 * would distort when it later fails.
 */
export function pictureSnippet(owner: string, repo: string, style: ServedStyle): string {
  return [
    `<picture>`,
    `  <source media="(prefers-color-scheme: dark)" srcset="${cardUrl(owner, repo, style, "dark")}">`,
    `  <img alt="${owner}/${repo} tech stack, generated by Stackshot" src="${cardUrl(owner, repo, style, "light")}">`,
    `</picture>`,
  ].join("\n");
}

// Sentence case, active voice, no filler, no trailing arrows. Collected here rather than
// scattered through JSX so the whole page can be read against DESIGN.md's copy rules in
// one pass — which is the only way that audit actually happens.
export const COPY = {
  headline: "Show your stack where people already look.",
  intro:
    "Paste a GitHub repo. Stackshot reads its manifests and draws the stack in layers, as a PNG that follows your README's light and dark themes.",
  inputLabel: "GitHub repo",
  placeholder: "github.com/owner/repo",
  generate: "Generate card",
  // Two phases, both real: one while /api/resolve runs, one while the card draws. The
  // button and the live region say the same thing, so a screen reader hears the page.
  reading: "Reading repo",
  drawing: "Drawing card",
  copyMarkdown: "Copy markdown",
  copied: "Markdown copied",
  copyFailed: "Select the snippet to copy it",
  downloadLight: "Download light PNG",
  downloadDark: "Download dark PNG",
  snippetTitle: "Paste this into your README",
  stackTitle: "What Stackshot found",
  exampleCaption: `An example card: ${EXAMPLE_REPO.owner}/${EXAMPLE_REPO.repo}, generated the same way yours will be.`,
  badUrl: "Stackshot reads GitHub repos. Paste a repo URL, or owner/repo.",
  // The per-IP gate and GitHub's own limit are one FailureReason but two different
  // sentences: one is about you, the other is about us.
  gateLimited: (limit: number) => `You've generated ${limit} cards this hour. Try again shortly.`,
  overflow: (n: number) => `+${n} more`,
  styleGroup: "Card style",
  style: { tiles: "Tiles", terminal: "Terminal" } satisfies Record<LaunchStyle, string>,
  themeGroup: "Preview theme",
  theme: { light: "Light", dark: "Dark", system: "System" } satisfies Record<ThemeMode, string>,
  // Says what the toggle is for, because it is the one control on the page that changes
  // nothing about what you copy. The snippet always carries both themes.
  themeNote: "This changes the preview. Your snippet always carries both themes.",
  // The card's own legend strings, not a second set: the description list is a key to the
  // card above it, so a layer renamed on one has to be renamed on both.
  layer: LAYER_NAME,

  // Nav and footer.
  wordmark: "stackshot",
  starOnGitHub: "Star on GitHub",
  github: "GitHub",
  builtBy: { before: "Open source. Built by ", name: "Ilerioluwa", after: "." },
  suggest: "Suggest a technology",

  // "One snippet. Both themes." — two lines in the design, and the break is deliberate.
  snippetPitchTitle: ["One snippet.", "Both themes."],
  snippetPitch:
    "Paste it into your README. GitHub shows the light card or the dark one to match each reader, and the card updates when your stack changes.",

  // The technology index.
  indexTitle: "Does it know your stack?",
  indexIntro: (n: number) => `Stackshot recognises ${n} technologies across four layers. Search for yours.`,
  indexAll: "All",
  indexSearchLabel: "Search technologies",
  indexSearchPlaceholder: "Search, e.g. prisma",
  indexShowAll: (n: number) => `Show all ${n}`,
  indexShowFewer: "Show fewer",
  indexNoMatch: (q: string) => `No match for "${q}".`,
  indexSuggest: "Suggest it on GitHub",
  indexSuggestAfter: " and it can join the map.",
  // Announced to a screen reader as the grid filters, since the change is visual only.
  indexCount: (n: number) => `${n} ${n === 1 ? "technology" : "technologies"} shown`,
} as const;
