import { cardFileName, type CardStyle } from "@/lib/card-style";
import type { Theme } from "@/lib/tokens";

/**
 * The one origin the card's footer, the preview and the copied snippet all agree on.
 * Overridable so `next dev` previews its own cards; the default is what ships, and what
 * strangers' READMEs will point at forever.
 */
export const SITE_ORIGIN = process.env.NEXT_PUBLIC_SITE_ORIGIN ?? "https://stackshot.ilerioluwa.com";

/** The repo whose card stands in the empty state. One line to change. */
export const EXAMPLE_REPO = { owner: "cybprom", repo: "stackshot" };

export function cardUrl(owner: string, repo: string, style: CardStyle, theme: Theme): string {
  return `${SITE_ORIGIN}/${owner}/${repo}/${cardFileName(style, theme)}`;
}

/**
 * The README snippet. Two rules, both about what happens after someone pastes it.
 *
 * The style is always written explicitly, never left to `card-{theme}.png`, so changing
 * the site's default never restyles a card already embedded in someone's README.
 *
 * No width or height on the img: one URL serves several heights — 1200×800, the error
 * card's 1200×518, and Tiles' content height — so a snippet copied while a repo worked
 * would distort when it later fails.
 */
export function pictureSnippet(owner: string, repo: string, style: CardStyle): string {
  return [
    `<picture>`,
    `  <source media="(prefers-color-scheme: dark)" srcset="${cardUrl(owner, repo, style, "dark")}">`,
    `  <img alt="${owner}/${repo} tech stack, generated by Stackshot" src="${cardUrl(owner, repo, style, "light")}">`,
    `</picture>`,
  ].join("\n");
}

// Sentence case, active voice, no filler, no trailing arrows. Collected here rather than
// scattered through JSX so the whole page can be read against DESIGN.md's copy rules in
// one pass — which is the only way that audit actually happens.
export const COPY = {
  headline: "Show your stack where people already look.",
  intro:
    "Paste a GitHub repo. Stackshot reads its manifests and draws the stack in layers, as a PNG that follows your README's light and dark themes.",
  inputLabel: "GitHub repo",
  placeholder: "github.com/owner/repo",
  generate: "Generate card",
  generating: "Generating card",
  copyMarkdown: "Copy markdown",
  copied: "Markdown copied",
  copyFailed: "Select the snippet to copy it",
  downloadLight: "Download light PNG",
  downloadDark: "Download dark PNG",
  snippetTitle: "Paste this into your README",
  stackTitle: "What Stackshot found",
  exampleCaption: `An example card: ${EXAMPLE_REPO.owner}/${EXAMPLE_REPO.repo}, generated the same way yours will be.`,
  badUrl: "Stackshot reads GitHub repos. Paste a repo URL, or owner/repo.",
  // The per-IP gate and GitHub's own limit are one FailureReason but two different
  // sentences: one is about you, the other is about us.
  gateLimited: (limit: number) => `You've generated ${limit} cards this hour. Try again shortly.`,
  overflow: (n: number) => `+${n} more`,
  layer: { frontend: "Frontend", backend: "Backend", infra: "Infra", tooling: "Tooling" },
} as const;
